### ISSUE TITLE
New serial port API

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/iot#1030]
I'm curious what you think about a replacement for `System.IO.Ports.SerialPort` with spans and async in mind (like suggested in https://github.com/dotnet/runtime/issues/27941) and maybe even based off the new `Pipelines` rather than `Stream`.

UWP also has [`SerialDevice`](https://docs.microsoft.com/en-us/uwp/api/windows.devices.serialcommunication.serialdevice) with features that are missing in `System.IO.Ports.SerialPort`. (Related: https://github.com/dotnet/runtime/issues/22597)

**Comment by joperezr** [comment]
Hello @danielchalmers thanks for the report. The code for SerialPorts actually lives in dotnet/runtime repo even though we use it a lot in here, but so that means that the right place to have this discussion is over in the issue that you pointed at. I have added @krwq to that issue since he is the owner of that library so he can help guiding through that discussion. I'll go ahead and close this one since as I explained this wouldn't really be the right place to change the API anyways.
