### ISSUE TITLE
Disabled test in Windows FastInterruptHandling

### ISSUE THREAD

**Issue by joperezr** [dotnet/iot#1054]
When adding changes for https://github.com/dotnet/iot/pull/1038 we actually noticed that the RaspberryPiDriver have never been tested in Windows, where it was also supported. That PR added testing for it, and one particular test (FastInterruptHandling) ended up being flaky failing some times. This same test is being also tested with the same code path by the WindowsDriver tests but seems like the extra level of inderection is causing RaspberryPiDriver to not be fast enough to detect the required edges for the test to pass. Logging this issue to track the investigation and fix so that the test can be re-enabled.

cc: @krwq

**Comment by pgrawehr** [comment]
Possibly related: #1004. I had already found that the test is considerably slower on Windows than on Linux. The reason is not so clear to me. Since the test should take a constant amount of time (it triggers a pin 100 times with an interval of 20ms) and this takes around 2.5 seconds on linux, but 3.5 seconds on Windows, it's likely to be related to the problem that Windows just cannot trigger pins fast enough.
