### ISSUE TITLE
Existing designs cannot add GPIO drivers externally

### ISSUE THREAD

**Issue by ZhangGaoxing** [dotnet/iot#1234]
#1130 Before writing the driver, I refer to the implementation of the existing driver. Due to the protection of some keywords, I cannot call the internal methods of `UnixDriver` outside the `System.Device.Gpio` package.

**Comment by krwq** [comment]
Hey @ZhangGaoxing can you elaborate on what should we change in System.Device.Gpio to make it easier for writing drivers like that?

**Comment by krwq** [comment]
@ZhangGaoxing is this unblocked now? Can you tell what's blocked still?

**Comment by ZhangGaoxing** [comment]
In fact, there is still this problem. So I inherited the `SysFsDriver` class directly. 

Here is a brief description of the error code.
```C#
// namespace Iot.Device.Gpio.Drivers
public unsafe class SunxiDriver : GpioDriver
{
    protected SunxiDriver()
    {
        _sysFSDriver = UnixDriver.Create();
    }

    protected override void ClosePin(int pinNumber)
    {
        // Error: CS1540
        _sysFSDriver.ClosePin(pinNumber);
    }
}
```

**Comment by pgrawehr** [comment]
True, creating "forwarding drivers" (drivers that use other drivers) is not possible right now due to protection levels. 

@joperezr This could only be solved by changing all the methods on GpioDriver to public, I suppose. Since that's not what we generally want, I currently see little possibility of fixing this. The use case is valid, though, as we actually do the very same internally already.

**Comment by krwq** [comment]
I'm personally in favor of making all `protected internal` public

**Comment by Ellerbach** [comment]
> I'm personally in favor of making all `protected internal` public

I agree. This will allow those kind of scenarios. And it will still keep everything super easy and straight forward for anyone who wants to use a simple GpioController without knowing the platform it's running on

**Comment by pgrawehr** [comment]
I basically agree as well, but we have to consider the risk that people start using the drivers directly, for which they're not intended. There must be some protection against directly working with the drivers.

**Comment by joperezr** [comment]
@pgrawehr has pointed out the issue with doing so, which is people will start using the drivers instead of the controllers, or just get confused with both having similar API surface. It was a very intentional design to make them protected internal. I would much rather move all drivers into System.Device.Gpio instead of making those members public. The controller does a bunch of pin management plus important checks that the driver doesn't do, so using the drivers directly is definitely not intended.

**Comment by joperezr** [comment]
To solve @ZhangGaoxing issue, one thing that could be done is that instead of having the pass-through driver call another driver directly, it should instead call a controller that uses that driver underneath, that way it is able to call all required methods.

**Comment by krwq** [comment]
@joperezr wouldn't that imply that GpioDriver is an implementation detail in System.Device.Gpio and it has no purpose for anyone implementing things outside of System.Device.Gpio?

**Comment by joperezr** [comment]
Yes and no. Having GpioDriver abstract class in S.D.Gpio is nice because then it is an extensibility point that other folks can use if they want to write a complete new driver from scratch outside the library and they can just use that to initialize the controller. The reason why the derived GpioDrivers are public (meaning RaspberryPi3Driver, SysFsDriver, etc) is to allow consumers to manually select which driver to use in case they don't want the one that would be automatically selected for them. In hindsight, I think the right way to do this might have been just having an enum to force a manual selection of a driver, without having to expose all of the derived drivers, but that ship has sailed.

**Comment by Ellerbach** [comment]
[Triage] @ZhangGaoxing are the existing work around acceptable?
