### ISSUE TITLE
Question: Why aren't packages released to NuGet.org more often?

### ISSUE THREAD

**Issue by hugener** [dotnet/iot#1250]

**Comment by joperezr** [comment]
Good question, we are going to ship our 1.1 release this month and we have been in talks in order to release stable versions much more often. In the past we were aligning with .NET Core shipping cycles, but there is no reason to continue to do that now so we will move to a much faster cadence (1 new release every 1-2 months).

**Comment by joperezr** [comment]
Closing the issue as the question is answered, but feel free to reopen if you have any follow ups.

**Comment by joperezr** [comment]
FYI: @richlander @krwq @Ellerbach

**Comment by dominikjeske** [comment]
I can see 1.1 nuget but no release on this page and no release notes?

**Comment by joperezr** [comment]
We just shipped it yesterday in NuGet and are working on tagging and finishing up the release notes now 😄

**Comment by joperezr** [comment]
Just pushed the release notes: https://github.com/dotnet/iot/releases/tag/1.1

**Comment by richlander** [comment]
I'm also hoping that we'll start shipping 1.2 previews pretty soon, hopefully this month.
