### ISSUE TITLE
Sample: Start application at device startup

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#13]
This would be a service/demon.

**Comment by joperezr** [comment]
Is the main idea of this to have just a line or two in the documentation to show how this should be done?

**Comment by krwq** [comment]
I can show how to do that, as I have already done that at home for my robot I was playing with.

What I did is started detached tmux by adding script to /etc/init.d and link in rc.d.

I tried to do that without tmux but without much success (I tried `nohup <myapp> &` but seems the app died quickly). Isn't crontab for scheduling rather than auto-start? Not sure how to add auto-start with that @wfurt, could you share an example? That would simplify it quite a bit if it is possible
