### ISSUE TITLE
Should GpioController NumberingScheme property be renamed to PinNumberingScheme 

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#137]
This is a small breaking change since it is public and will most likely be understood what numbering scheme the property is related to hence the enum type.

```csharp
// Within the GpioController.cs file.
public GpioController(PinNumberingScheme numberingScheme, GpioDriver driver)
public PinNumberingScheme NumberingScheme { get; }
```

If not renamed, then the other GpioController files should be updated to be consistent.

```csharp
// Within the GpioController.Linux.cs and GpioController.Windows.cs files.
public GpioController(PinNumberingScheme pinNumberingScheme)
  : this(pinNumberingScheme, GetBestDriverForBoard())
{
}

**Comment by joperezr** [comment]
Usually as long as you stay in C#, having a property name match a type name is fine. That said, some other languages won't allow this, and so in scenarios like sending a serialized version of data from c# over to a web client (written in a different programming language) might have issues parsing or understanding why does the type name match the property name. Because of this reason, I thought of keeping them different by not matching exactly what the type name is. Here is a stackoverflow discussion about it: https://stackoverflow.com/questions/525319/what-to-do-when-property-name-matches-class-name

All that said, we only originally did this to prevent issues like this in the future, but if that is not considered a valid concern we could re-think this and rename if necessary.
