### ISSUE TITLE
Add bindings for DS18B20 - Digital temperature sensor

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#172]

**Comment by maloo** [comment]
Hi, I can help,
I need to write a driver for a MAX31820, I guess these are very similar. Do you have any API. Do you want a 1-wire device and a device driver or just a device driver?

**Comment by joperezr** [comment]
Hello @maloo, I know that @ericstj was planning on working on this one as well. He is planning to add support for 1-Wire into our main library. I'm not sure if he is planning to also write a device binding for the actual sensor, so just an FYI so that you don't both end up doing the same work :smile:

**Comment by krwq** [comment]
let me update this and other issues so that we don't end up investigating

**Comment by joshfree** [comment]
removing the up-for-grabs label as @ericstj grabbed this along with general 1-WIRE support.

@ericstj if your plans change please flip this back to up-for-grabs.  Thanks

**Comment by MaklaCof** [comment]
Is there something new. I would like to replace really my old device for measuring hot water in boiler with a new one, based on RaspberryPI. The best suited sensor for this is DS18B20.

**Comment by maloo** [comment]
Waiting for @krwq to hit the merge button of #793

**Comment by krwq** [comment]
This is merged already, thanks @maloo!
