### ISSUE TITLE
.NET IoT needs a logo

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#233]
This is more of a fun geek-out than anything, but it seems like this repo/project should have some type of logo to represent.  You can see other project logos on the [.NET Foundation site](https://dotnetfoundation.org/) like Prism, etc.

/cc @joperezr @richlander any thoughts or resources that could design something?

**Comment by joshfree** [comment]
@shaggygi any brainstormy ideas for a specific logo that would scale well in size?

**Comment by shaggygi** [comment]
Not really, but pinging @jongalloway as he might have some willing/designer resources from the .NET Foundation.

**Comment by shaggygi** [comment]
I also tried pinging @BethMassi, but no word back as of yet.

**Comment by shaggygi** [comment]
What about the image used in the .NET Core slides?  If so, where can we find it?

![image](https://user-images.githubusercontent.com/2956825/61787701-5d3af280-adde-11e9-9d3f-35c777418a57.png)

**Comment by jongalloway** [comment]
@shaggygi That image looks like it's from shutterstock: https://www.shutterstock.com/image-vector/internet-things-vector-icon-iot-symbol-573776821?src=8x8o92J1ljPmUcgDwHXqGQ-2-65 (see below)

Things that are directly under the .NET brand / marketing at Microsoft are  more restricted on logos, since they fall under Microsoft branding guidelines. @BethMassi?

![IoT logo](https://image.shutterstock.com/image-vector/internet-things-vector-icon-iot-600w-573776821.jpg "IoT logo")

**Comment by BethMassi** [comment]
The only official logo we are allowed to have is the .NET logo (".NET" in Segoe font in purple box). 
https://github.com/dotnet/swag/tree/master/netlogo 

Are you trying to use an image/icon in a product somewhere to differentiate the workload? We use the Visual Studio design team to do that typically.

**Comment by shaggygi** [comment]
> Are you trying to use an image/icon in a product somewhere to differentiate the workload?

Yeah, trying to come up with a good icon for the .NET IoT repo.

**Comment by Ellerbach** [comment]
@shaggygi still interested in this? Or should we close this issue?

**Comment by shaggygi** [comment]
@Ellerbach I'll go ahead and close.  Never got any traction while trying to reach out to others that might have some designer contacts.  We can open later if needed.  Thx
