### ISSUE TITLE
Should devices folder be capitalized

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#617]
Not really a biggie, but should the [devices folder](https://github.com/dotnet/iot/tree/master/src/devices) by capitalized to be consistent with others?

![image](https://user-images.githubusercontent.com/2956825/61661054-3921c900-ac99-11e9-8a18-e286ad6932e8.png)

**Comment by krwq** [comment]
I'd refrain from doing that at least until we ship 3.0

**Comment by joperezr** [comment]
I don't think we should do this. The other folders are capitalized only because they have the libraries names, which are capitalized. We would have to change many other folders if we wanted to do this, like "src" and "tools" or "samples". Making all of these changes might have unintended consequences on other OSes and it also doesn't echo the model we have followed in corefx and the rest of our repos.

**Comment by shaggygi** [comment]
> because they have the libraries names

Yeah, that's what I was thinking... but wasn't completely sure.  I'd say leave as in since src, tools and such are similar.  Close if no further work is needed.  Thx
