### ISSUE TITLE
RTC devices not setup for device-listing

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#632]
I haven't looked in any detail, but it seems like the recent changes/addition to [Rtc binding folder](https://github.com/dotnet/iot/tree/master/src/devices/Rtc) doesn't work with [device-listing](https://github.com/dotnet/iot/tree/master/tools/device-listing) generation now.

**Comment by krwq** [comment]
let me re-gen and see what's going on

**Comment by krwq** [comment]
@shaggygi device-listing is not being auto-generated - you have to manually run the tool (I've found manual better so far since it gives me a chance to review the changes). When I run `dotnet run` on device-listing dir I'm seeing:

```
Warning: /home/krwq/work/iot/src/devices/SoftwareSpi/category.txt is missing
Warning: /home/krwq/work/iot/src/devices/Rtc/category.txt is missing
```

so that seems to be a culprit - I'll fix it and send PR with the changes

**Comment by shaggygi** [comment]
Yeah, i noticed that, which is a nifty utility.  It seemed like it wasn’t generating for Clocks section.
