### ISSUE TITLE
System.Device.Gpio needs xml doc comments 

### ISSUE THREAD

**Issue by joshfree** [dotnet/iot#72]

**Comment by shaggygi** [comment]
@joshfree @joperezr If time allows, I'll try to review and add summaries for PWM code next.  Is there something else outstanding for this I should focus on to consider this complete?

**Comment by joperezr** [comment]
Thanks so much for all the hard work you've been doing for this issue @shaggygi, I believe you are right and PWM is the only area we are missing now. For the device-bindings we are treating xml-comments as a nice-to-have right now but we aren't enforcing them, so this issue is only set to cover the System.Device.Gpio library.

**Comment by shaggygi** [comment]
No prob.  It's been a fun exercise and helped learn more about the inner-workings of the API along the way.  Hope do help lots more in future, as well. :smile:

**Comment by shaggygi** [comment]
We should be able to close this one now.

**Comment by joperezr** [comment]
Agreed, thanks for all the hard work @shaggygi
