### ISSUE TITLE
SPI TFT Screen for ILITEK

### ISSUE THREAD

**Issue by alberk8** [dotnet/iot#819]
**Is your feature request related to a problem? Please describe.**

Is there any plan development for the ILITEK SPI display chipset ILI9341 and ILI9486 ?  Thank you.

**Comment by krwq** [comment]
I have ILI9341 code somewhere in my private branches and can add basic support relatively quickly, it just needs some clean up. I'm kinda busy this week and early next week so please remind me if you don't see any PR in the next two weeks

**Comment by krwq** [comment]
Just made it public: https://github.com/krwq/iot/tree/ILI9341 is my WIP branch from half a year ago in case you need it now

**Comment by alberk8** [comment]
Thank you so much.

**Comment by alberk8** [comment]
> I have ILI9341 code somewhere in my private branches and can add basic support relatively quickly, it just needs some clean up. I'm kinda busy this week and early next week so please remind me if you don't see any PR in the next two weeks

Is the PR going to happen soon?  Thanks.

**Comment by krwq** [comment]
@alberk8 haven't had time yet but this is really high on my TODO list at this point so might happen soonish

**Comment by davidjmallar** [comment]
Is it soonish yet? :)

**Comment by krwq** [comment]
Sorry, I don't think I'll find time for this anytime soon... I've moved out since then, the TFT screen is in one of the boxes somewhere which I haven't unpacked yet and I don't really have time to do this unless I find some interesting project which needs the screen... Feel free to pick up my branch and go from there if you feel like it... I'll update this thread if something changes. If you start working on this please write so in the thread so we don't accidentally duplicate.

**Comment by dotMorten** [comment]
@krwq I took your branch and updated it a bit to better match how the other displays work. Would you mind if I continued your work and made a PR for it? (I'll fork from yours so you still get some of the credit)

**Comment by krwq** [comment]
go ahead, having a binding matters more than credit 😄

**Comment by dotMorten** [comment]
Awesome! PR linked above.

**Comment by krwq** [comment]
[Triage] ILI9341 is already merged. Closing this issue since we're not tracking binding requests (send PR 😄)
